### ISSUE TITLE
Does epiTCR also provide binding strength between antigen sequence and TCR? so that the tool can be used to rank the antigen for immunogenicity ?

### ISSUE THREAD

**Issue by ravinpoudel** [ddiem-ri-4D/epiTCR#2]
Does epiTCR also provide binding strength between antigen sequence and TCR? so that the tool can be used to rank the antigen for immunogenicity ?

**Comment by nttvy** [comment]
Hi @ravinpoudel 

I appreciate your interest on the tool.

So far, epiTCR does not provide the binding strength between the antigen sequence and TCR. It only provides the possibility of the binding between the antigen and TCR. Therefore, it cannot really be used to rank the antigen.

We are still working on further improvements to epiTCR. In particular, we are trying to solve the problem of predicting unseen peptides, the relationship between the binding strength and binding possibility, or a way to predict the binding strength, and use the binding possibility/binding strength as antigen ranking features. 

But this will take time because these problems are very challenging.
