### ISSUE TITLE
Describe the input file

### ISSUE THREAD

**Issue by ssuthram-gilead** [ddiem-ri-4D/epiTCR#7]
I am trying to use this tool to predict whether a specific CDR3b sequence binds to an antigen.  However, when I run the pedict.py with just this information, it throws an error.  I don't have MHC or HLA information.

**Comment by ssuthram-gilead** [comment]
I am trying to run the prediction method and am getting the following error:
File "/home/ssuthram/epiTCR/predict.py", line 35, in <module>
    model_rf = pickle.load(open(modelfile, 'rb'))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_pickle.UnpicklingError: A load persistent id instruction was encountered, but no persistent_load function was specified.

**Comment by ddiem-ri-4D** [comment]
The error you are encountering (`_pickle.UnpicklingError: A load persistent id instruction was encountered, but no persistent_load function was specified.`) suggests that there might be an issue with the pickled object that you are trying to load. This could be due to several reasons, including version mismatches or corruption of the pickled file.

Here are a few suggestions to debug and fix the issue:

- Check Python Versions: Make sure that you are using the same version of Python to save and load the model. I saved the model using Python 3, try loading it with Python 3.
- Check Library Versions: Verify that the versions of the libraries you are using (such as `numpy`, `pandas`, `imblearn`, `tqdm`, etc.) are consistent between the saving and loading environments. Inconsistencies can lead to issues during unpickling.
- Use joblib Instead: As mentioned earlier, consider using joblib for serialization of scikit-learn models. It is more efficient for large objects and may handle certain cases better.

```
from joblib import load
# Load model
model_rf = load(open(modelfile, 'rb'))
```

- Check File Integrity: Ensure that the file (`modelfile`) is not corrupted. If the file is corrupted, you may need to recreate it.
- Use Full Paths: Provide full paths for the `modelfile` and `testfile` in your script to avoid any path-related issues.
- Check Dependencies: Ensure that the dependencies used in the training environment are the same as those in the testing environment.

Hope this is helpful for you.

Best regards,
Diễm

**Comment by ilovegreentea** [comment]
> I am trying to use this tool to predict whether a specific CDR3b sequence binds to an antigen. However, when I run the pedict.py with just this information, it throws an error. I don't have MHC or HLA information.

how did you solve this?
I' don't have MHC or HLA information too.

and can i use this with scTCR-seq?

**Comment by ddiem-ri-4D** [comment]
> > I am trying to use this tool to predict whether a specific CDR3b sequence binds to an antigen. However, when I run the pedict.py with just this information, it throws an error. I don't have MHC or HLA information.
> 
> how did you solve this? I' don't have MHC or HLA information too.
> 
> and can i use this with scTCR-seq?

**Comment by ddiem-ri-4D** [comment]
> > > I am trying to use this tool to predict whether a specific CDR3b sequence binds to an antigen. However, when I run the pedict.py with just this information, it throws an error. I don't have MHC or HLA information.
> > 
> > 
> > how did you solve this? I' don't have MHC or HLA information too.
> > and can i use this with scTCR-seq?

**Comment by ddiem-ri-4D** [comment]
Hi @ilovegreentea 

Has your issue been resolved?

**Comment by ilovegreentea** [comment]
@ddiem-ri-4D 
Thank you for asking.

I still haven't solved it

**Comment by ddiem-ri-4D** [comment]
Hi @ilovegreentea 
Could you show me the details of the error you are encountering?

**Comment by ilovegreentea** [comment]
@ddiem-ri-4D 
I didn't run yet, but when i see test data, there are CDR3b,epitope,HLA,binder,MHC
but my data have only CDR3 sequence among them... is it possible to run this?

Colnames of my data below : 
 "barcode"  "sample"   "TCR1"     "cdr3_aa1" "cdr3_nt1" "TCR2"     "cdr3_aa2" "cdr3_nt2" "CTgene"   "CTnt"     "CTaa"     "CTstrict" "cellType"

Thank you for making great tool..

**Comment by ddiem-ri-4D** [comment]
Hi @ilovegreentea 
Sorry, but my input must include CDR3b, epitope, with or without HLA. If your input only includes TCR information, you can use other tools like TCRdist, ImmunoMap, TCRMatch, etc. Sorry, I haven't researched the scTCR-seq tool yet, so I can't recommend it to you. You might want to look into it; it might be suitable for you.
In that case, your problem isn't really about predicting TCR-peptide binding anymore, is it?  ^^

**Comment by ilovegreentea** [comment]
@ddiem-ri-4D 
I got it.
Thank you for answering my stupid question.
